### ISSUE TITLE
Update tutorials with Android-only configuration and obstacle avoidance

### ISSUE THREAD

**Issue by adamantivm** [ekumenlabs/tangobot#100]
Add these two new options to the tutorials in ros.wiki.org:

 - Using man_nav to run a fully-Android configuration
 - Visualizing and using obstacle avoidance

Also review all the existing tutorials for accuracy after the update to tango_ros_node 1.1

**Comment by jubeira** [comment]
Done!
Check http://wiki.ros.org/tangobot/tutorials/kinetic/installation and
http://wiki.ros.org/tangobot/tutorials/kinetic/empty%20map%20navigation
