### ISSUE TITLE
Make new demo video using Android client

### ISSUE THREAD

**Issue by adamantivm** [ekumenlabs/tangobot#101]
Create an updated video that better shows off Tangobot's capabilities, including:
 - Fully Android configuration
 - Obstacle avoidance
 - (optional) using fixed obstacle map

**Comment by adamantivm** [comment]
Note the first step for this is to define a rough outline

**Comment by jubeira** [comment]
https://www.youtube.com/watch?v=wMVe8XacbUE

**Comment by patricioreyna** [comment]
Really nice video indeed!
We should share it from our Ekumen twitter account ?  I'd definitely
retweet it :)
