### ISSUE TITLE
Final tweaks for map_nav

### ISSUE THREAD

**Issue by adamantivm** [ekumenlabs/tangobot#103]
Any necessary tweaks for map_nav to work properly with Tangobot.

Off the bat:
 - Prevent 'set_pose' from changing the location on the map, since it doesn't do so on the robot

**Comment by jubeira** [comment]
I think this one is done.
Perhaps (just thinking out loud here) it would be good to see how hard it is to subscribe to the inflation layer of the costmap, and display that layer with different colors. Right now, we are only displaying the occupancy grid, so the whole inflation layer is displayed as a black stain, which is not quite accurate.

**Comment by jubeira** [comment]
Displaying different colors was not trivial, so we are sticking to black for now. In any case, that would be a separate issue.
