### ISSUE TITLE
Support for Asus Zenphone AR

### ISSUE THREAD

**Issue by adamantivm** [ekumenlabs/tangobot#110]
This depends on the Tango ROS Node being updated to support the phone.

After this is done:
 - [x] Make sure Tangobot code works well in this phone
 - [x] Create and print a new 3D mount
 - [x] Update calibration settings / configuration
 - [ ] Update hardware tutorials

**Comment by jubeira** [comment]
Done in #126.
Tutorials updated: 
 - http://wiki.ros.org/Robots/Tangobot
 - http://wiki.ros.org/tangobot/tutorials/kinetic/hardware%20setup
