### ISSUE TITLE
Global and local planner plugin libs are not loaded

### ISSUE THREAD

**Issue by JzHuai0108** [ekumenlabs/tangobot#131]
Dear Sir,

I am facing the problem that the global and local costmap do not show up when running move_base on an android phone.

For the android setup, the navigation rviz is given below, note the warnings about unavailable costmaps.
![Screenshot from 2023-06-29 12-46-18](https://github.com/ekumenlabs/tangobot/assets/8062561/09a433f6-b277-4a5c-9097-b80b3505afa7)

And the tf tree looks perfect as shown below.
![frames](https://github.com/ekumenlabs/tangobot/assets/8062561/ab6b27d5-cf26-4dfb-ac8e-25d375f0c1e0)

Moreover, the move_base works perfectly on Ubuntu 18.

I tried to solve this issue with several approaches suggested elsewhere, but none worked.
I currently have built the [roscpp_android](https://github.com/JzHuai0108/roscpp_android) with the kinetic ros libraries, but I mixed these libraries with the navigation modules of the melodic version, because I succeeded in testing these navigation modules on Ubuntu 18.
The roscpp_android built successfully,  the AMCL runs fine on android, and the move_base also works except that the costmap is unable to be created as discussed above.

Do I need to stick with kinetic in all navigation modules?

**Comment by wfskxj** [comment]
However, when I run it on another device with Android 7.1, I encountered the following error：
org.ollide.rosandroid A/libc: /usr/local/google/buildbot/src/android/ndk-release-r18/external/libcxx/../../external/libcxxabi/src/abort_message.cpp:73: abort_message: assertion "terminating with uncaught exception of type pluginlib::LibraryLoadException: According to the loaded plugin descriptions the class costmap_2d::StaticLayer with base class type costmap_2d::Layer does not exist. Declared types are " failed

**Comment by JzHuai0108** [comment]
I made sure that "LOCAL_WHOLE_STATIC_LIBRARIES" is added in the android.mk. I also made sure that the root failure cause is the failure to load the relevant plugin libraries. But the problem persists.

**Comment by JzHuai0108** [comment]
Brute force makes miracles. I turned all runtime plugins into static libraries linked at compile time. Then, the move_base can show cost maps.
