### ISSUE TITLE
Make a demo video

### ISSUE THREAD

**Issue by adamantivm** [ekumenlabs/tangobot#86]
- [ ] Define the storyline
 - [ ] Film
 - [ ] Edit
 - [ ] Upload
 - [ ] Link to ROS tutorial page
 - [ ] Share with Google sponsors

**Comment by jubeira** [comment]
I think this one can be closed too

**Comment by adamantivm** [comment]
I agree. But I suggest deleting the old one and pasting here a link to the final one for completeness, then closing the issue.

**Comment by gecofernando** [comment]
New video's link: https://youtu.be/kR_cJSCLBTg

**Comment by gecofernando** [comment]
Old video was removed from youtube.
