### ISSUE TITLE
Tangobot ROS.org wiki page does not refer to Play Store

### ISSUE THREAD

**Issue by juergensturm** [ekumenlabs/tangobot#93]
Currently none of the wiki pages on Tangobot mention that the app is available on Play Store. I would suggest to add it in several places to make sure that people are aware of it and can find it easily. Also, please link the video from the Tangobot main wiki page (similar to http://wiki.ros.org/tango_ros_streamer).

**Comment by jubeira** [comment]
Yes, currently it's only mentioned in the installation step but there's no link to the app.
I will fix that!

**Comment by jubeira** [comment]
Done!
@adamantivm I think the link in the Play Store is still pointing to the first version of the video.
I just put the link to the new one in Tangobot's main wiki page. Can you fix that?

**Comment by adamantivm** [comment]
Yes, this is on my plate. Unfortunately it's not trivial and I haven't had the time to finalize it yet.
It will be done between today and early next week.

**Comment by jubeira** [comment]
I think we can close this one; the video in the wiki and the playstore now point to the second version.

**Comment by juergensturm** [comment]
Sounds good, thanks!
